# Site settings
title: map-inspector
email: ""
description: > # this means to ignore newlines until "baseurl:"
 Simple map to inspect OSM objects
baseurl: "/map-inspector" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
